### ISSUE TITLE
无法打开包括文件: “httplib.h”

### ISSUE THREAD

**Issue by CARASO** [thatboy-echo/HttpClient#1]
HttpClient\HttpClientDlg.h(5,10): fatal error C1083: 无法打开包括文件: “httplib.h”: No such file or directory

**Comment by thatboy-echo** [comment]
httplib.h为C++的http库，见[项目地址](https://github.com/yhirose/cpp-httplib)，我刚在仓库中也提交了这份[文件](https://github.com/thatboy-echo/HttpClient/blob/master/httplib.h)。
